### ISSUE TITLE
Is it possible to power off the display

### ISSUE THREAD

**Issue by ohmyarch** [antonok-edm/ssd1309#1]
something like:
https://docs.rs/ssd1306/0.4.2/ssd1306/mode/graphics/struct.GraphicsMode.html#method.display_on

**Comment by antonok-edm** [comment]
It wasn't before, but I just added it in e922ba4274651f2e7b9e351673f9eb505f744308 :smile:

**Comment by antonok-edm** [comment]
Now published in [v0.2.1](https://crates.io/crates/ssd1309).
