### ISSUE TITLE
How to run the test

### ISSUE THREAD

**Issue by Angr1st** [antonok-edm/ssd1309#6]
Hi @antonok-edm , I'm trying to update the dependencies for ssd1309. I am mostly incrementing embedded-graphics-core and embedded-graphics versions but have also updated the dev-dependencies. My biggest issue is that I cannot run the tests. I get this error:
```
cargo test --target thumbv7em-none-eabihf
   Compiling ssd1309 v0.4.0 (/mnt/c/Users/Torben/source/repos/Rust/ssd1309)
error[E0463]: can't find crate for `test`
   --> src/builder.rs:143:5
    |
142 |       #[test]
    |       ------- in this procedural macro expansion
143 | /     fn test_output_pin() {
144 | |         let p = NoOutputPin::new();
145 | |         let _d = SomeDriver { p };
146 | |
147 | |         assert!(true);
148 | |     }
    | |_____^ can't find crate
    |
    = note: this error originates in the attribute macro `test` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0463]: can't find crate for `test`

error: `#[panic_handler]` function required, but not found

For more information about this error, try `rustc --explain E0463`.
error: could not compile `ssd1309` (lib test) due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
```

My question is basically how to run the tests?

**Comment by antonok-edm** [comment]
@Angr1st hmm, that's a good question actually. I don't think I've actually run the tests in this crate myself; I just cargo-culted them over from [`sh1106`](https://github.com/jamwaffles/sh1106) originally. You might want to check there and see if there's any more information?

Otherwise, I've just been using the examples directory for testing.

Thanks for working on this, btw!

**Comment by antonok-edm** [comment]
Oh, you might also want to try compiling/running the tests with a `--target` native to your development computer, rather than `thumbv7em-none-eabihf`. I don't see any embedded-specific code in that particular test at least.

**Comment by Angr1st** [comment]
running it with my regular target x86_64-unknown-linux-gnu in wsl gives me cc linker errors. I dug around a little and it seems like the tests for no_std only run on the target computer, but I will ask in the sh1106 repo if they have a way to run the tests.

**Comment by Angr1st** [comment]
The author of the ```sh1306``` told me the correct invocation [here](https://github.com/jamwaffles/sh1106/issues/33). The regular test runs fine but the doc tests fail.
