### ISSUE TITLE
Some JOY-IT 2.42 inch SSD1309 screens do not work with this crate (but do work using MicroPython)

### ISSUE THREAD

**Issue by barafael** [antonok-edm/ssd1309#8]
I'm using [this 2.42in SSD1309-based display](https://www.pollin.de/p/joy-it-2-42-oled-display-com-oled2-42-811347) and a variant of it which has a black PCB but otherwise **supposedly** same specs.

My problem is that both models behave differently when driven using this library. Basically, the "green variant" PCB works fine, while the "black variant" PCB does not reliably work. It frequently NAKs the bus. However, I do note that **both displays work fine using MicroPython**.

I am driving the displays using an RP2040, bog standard raspberry board, using I2C0 on GP0/GP1.

## Test Program

Initialize display, then, while PIN 5 is held low, draw a progressbar (rectangle) from 0 to 100 percent, restarting from 0.

[Demo code using embassy](https://github.com/barafael/rp2040-display-demo)
Additionally, the code blinks the LED on the other Core to show the program is running.

[demo.py](https://github.com/barafael/rp2040-display-demo/blob/main/demo.py)
Note this uses the 1306 driver and works just fine on both displays, most of the time. By most of the time, I mean that it does very rarely get NAKs on the bus. This I also observe when I use the Rust ssd1306 driver, so I assume it is just SSD1306/SSD1309 difference. The hangs I observe on Rust with SSD1309 driver I can also observe when using Rust with SSD1306 driver.

## I2C Traces

**These are not really ZIP files**, they are `.sal` files which may be opened using Saleae Logic. GitHub allows `.zip` upload, but not `.sal`. I can provide CSV, too.

I recorded these I2C traces of the I2C bus traffic with the rust program:
[pico-rust-ssd1309.zip](https://github.com/antonok-edm/ssd1309/files/14186248/pico-rust-ssd1309.zip)

I recorded these I2C traces of the I2C bus traffic with the python program:
[pico-python-ssd1309.zip](https://github.com/antonok-edm/ssd1309/files/14186004/pico-python-ssd1309.zip)

## Observations on the Traces

30k feet view of one transaction by the rust program:
![image](https://github.com/antonok-edm/ssd1309/assets/6966738/05868a93-d5ba-4f98-bae6-0445d5b55aa0)

30k feet view of one transaction by the python program:
![image](https://github.com/antonok-edm/ssd1309/assets/6966738/38ff6946-03b5-4f08-87ba-93d83bbe64fa)

It seems the SDA line is significantly more busy using the Rust driver, which may overwhelm the one type of display which I have.

**Comment by antonok-edm** [comment]
@barafael thanks for reporting!

Does the Rust program itself continue executing without a functioning display, or does it hang/panic somewhere?

**Comment by barafael** [comment]
The rust program does not panic, I just get BusWriteError on any of the display operations. That means a NAK happened, the i2c slave was overwhelmed (I think).
I can soon share traces of the bus write error occurring, if that would be useful.

**Comment by barafael** [comment]
Actually it may be that the hardware is just not complying to ssd1309, and for some reason in python it works anyway, but I do wonder why

**Comment by antonok-edm** [comment]
Can you also try reducing the I2C clock speed? I see you're using the same 400kHz in both programs, but it'd be good to know if modifying it affects the issue.

> Actually it may be that the hardware is just not complying to ssd1309, and for some reason in python it works anyway, but I do wonder why

FWIW, if there's a simple way to get your display supported by this crate I'd be happy to do it (even if it's not technically up to spec for some reason). I think it's relatively common that some displays have their own "quirks".

**Comment by barafael** [comment]
Ah yes I forgot to write. 100kHz does not make a difference at all. Maybe that means it isn't a buffer size issue?

**Comment by barafael** [comment]
I am running that same JOY-IT display type just fine using SPI (even at 2MHz). This means I think I won't be investigating the not-working i2c anymore if I can get the pinout change to work. If you want I can send you a display where this crate doesn't seem to work with i2c, just let me know should you want it. 

Regardless, then we can close this issue I guess?
